[package]
name = "rust-cpu"
version = "0.1.0"
authors = ["bankent1 <bankent1@email.arizona.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
